app:
    resource: '@AppBundle/Controller/'
    type: annotation

recetas_list:
    path: /recetas/
    defaults: { _controller: RecetasBundle:Receta:list }

recetas_show:
    path: /recetas/{receta_name}
    defaults: { _controller: RecetasBundle:Receta:show }

#Ejercicio 2.2
recetas_show:
    path: /recetas/{receta_id}
    defaults: {_controller: RecetasBundle:Receta:show }
    requirements:
        receta_id: \d+

#TEMA-5
#Nueva ruta al formulario
mis_recetas_author_create:
    pattern: /authors/create
    defaults: { _controller: RecetasBundle:Author:create }

#TEMA-8
#Autenticación formularios. El nombre de la ruta login tienen que coincidir con los valores de security.yml
login:
    path: /login
    defaults: { _controller: RecetasBundle:Security:login }

#Es necesario añadir una ruta de salida para el logout
logout:
    path: /logout

