#src/RecetasBundle/Resources/config/doctrine/Author.orm.yml

RecetasBundle\Entity\Author:
  type: entity
  #indicar a Doctrine que la entidad Author esta gestionada por mi propio repositorio
  repositoryClass: RecetasBundle\Repository\AuthorRepository
  table: authors
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    surname:
      type: string
      length: 255
  #para una relación bidireccional y que el author contenga una referencia a sus recetas
  oneToMany:
    recipes:
      targetEntity: Receta
      mappedBy: author
