# src/RecetasBundle/Resources/config/doctrine/Ingredient.orm.yml
RecetasBundle\Entity\Ingredient:
  type: entity
  table: ingredients
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255