#src/RecetasBundle/Resourcer/config/doctrine/Receta.orm.yml

RecetasBundle\Entity\Receta:

  type: entity
  table: recetas
  #una relaci칩n muchos a uno Recetas-Author
  manyToOne:
    author:
      targetEntity: Author
      #la carga Eager, para que se carguen todas las entidades relacionadas con author
      fetch: EAGER
      #La carga Lazy, el objeto author asociado a Receta no ser치 cargado hasta el momento en que sea necesario, por ejemplo, cuando se ejecute: receta->getAuthor();
      fetch: LAZY
      joinColumn:
        name: author_id
        referencedColumnName: id
        #para configurar el borrada en cascada a nivel de BBDD
        onDelete: "CASCADE"
      #Para asociar la operaci칩n en casca y guardar las entidades asociadas
      cascade: ["persist"] 
      inversedBy: recetas
  #una relaci칩n muhcos a muchos Recetas-Ingredients
  manyToMany:
    ingredients:
      targetEntity: Ingredient
      joinTable:
        name: receta_ingredients
        joinColumns:
          receta_id:
            referencedColumnName: id
        inverseJoinColumns:
          ingredient_id:
            referencedColumnName: id
      cascade: ["persist"] 
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 255
    difficulty:
      type: string
      length: 40
    description:
      type: text

       